#! /bin/bash
#Deteção da versão do (?)Ubuntu

#2-do - Adicionar e testar funcionalidade no Debian e variantes.

#Xubuntu
if (dpkg --get-selections | grep -q xubuntu); then
	VERSAUM="XUBUNTU"
fi
#Lubuntu
if (dpkg --get-selections | grep -q lubuntu); then
	VERSAUM="LUBUNTU"
fi
#Mint
if (dpkg --get-selections | grep -q mint); then
	VERSAUM="MINT"
fi
#Ubuntu (Default)
if [ -z "$VERSAUM" ]; then
	VERSAUM="UBUNTU"
fi

echo $VERSAUM
exit
