#! /bin/bash

#Deteção da versão do (?)Ubuntu
#2-do - Adicionar e testar funcionalidade no #!

#Xubuntu
if (dpkg --get-selections | grep -q xubuntu); then
	VERSAUM="XUBUNTU"
fi
#Lubuntu
if (dpkg --get-selections | grep -q lubuntu); then
	VERSAUM="LUBUNTU"
fi
#Kubuntu
if (dpkg --get-selections | grep -q kubuntu); then
	VERSAUM="KUBUNTU"
fi
#Mint
if (dpkg --get-selections | grep -q mint); then
	VERSAUM="MINT"
fi
#Ubuntu (Default)
if ($VERSAUM); then
else
	VERSAUM="UBUNTU"
fi

echo $VERSAUM
exit
